
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0
    force_no_accel = 0
    accel_profile = flat 
    # numlock_by_default = true

    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = yes
    }

}



# for window shallow similar to devour
misc {
    enable_swallow = true
    swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|org.wezfurlong.wezterm)
}

# Don't show update on first launch
ecosystem {
  no_update_news = true
}


# ╔──────────────────────────────────────────╗
# │╔═╗┬ ┬┌─┐┌┬┐┌─┐┌┬┐  ╦╔═┌─┐┬ ┬╔╗ ┬┌┐┌┌┬┐┌─┐│
# │║  │ │└─┐ │ │ ││││  ╠╩╗├┤ └┬┘╠╩╗││││ ││└─┐│
# │╚═╝└─┘└─┘ ┴ └─┘┴ ┴  ╩ ╩└─┘ ┴ ╚═╝┴┘└┘─┴┘└─┘│
# ╚──────────────────────────────────────────╝


$d=[$ut|User Preferences]
bindde = , xf86KbdBrightnessDown, $d decrease keyboard brightness, exec, $scrPath/BrightnessKbd.sh --dec # decrease keyboard brightness
bindde = , xf86KbdBrightnessUp, $d increase keyboard brightness, exec, $scrPath/BrightnessKbd.sh --inc # increase keyboard brightness

bindd = $mainMod, N, $d open cherrytree, exec, cherrytree
bindd = $mainMod Shift, N, $d open sublime, exec, subl
bindd = $mainMod, O, $d open occt-root, exec, /usr/local/bin/occt-root
bindd = $mainMod, Y, $d open youtube, exec, ~/.local/bin/youtube-app
bindd = $mainMod, W, $d open webui, exec, /usr/bin/chromium --app=http://localhost:3000 --ozone-platform-hint=auto --disable-gpu-sandbox
bindd = $mainMod Shift, P, $d open playlist, exec, zen-browser "https://www.pornhub.com/playlist/347252581"
bindd = $mainMod Shift, R, $d reboot system, exec, $scrPath/reboot.sh
bindd = $mainMod Shift, S, $d shutdown system, exec, $scrPath/shutdown.sh

# Use bindrd for dictate so it executes ON RELEASE to prevent typing out text while Super+M is held down
bindrd = $mainMod, m, $d dictate, exec, ~/.local/bin/dictate
bindd = $mainMod Shift, M, $d read aloud, exec, ~/.local/bin/read-aloud


# Application shortcuts
bindd = $mainMod, V, $d open virt-manager, exec, virt-manager
bindd = $mainMod, Return, $d open kitty, exec, kitty
bindd = $mainMod ALT, B, $d open torbrowser, exec, /home/z3ncoding123/.local/share/flatpak/app/org.torproject.torbrowser-launcher/x86_64/stable/9b3ebdceda0d23a61888b21c6d72a707cc72c41b3c908a5a2e6b769f156c2c46/files/bin/torbrowser-launcher
#bind = $mainMod, E, exec, $file
#bind = $mainMod, N, exec, $editor
#bind = $mainMod+Shift, N, exec, cherrytree
#bind = $mainMod, B, exec, $browser
#bind = Ctrl+Shift, Escape, exec, xfce4-taskmanager
#bind = $mainMod, C, exec, code
#bind = $mainMod Shift, C, exec, pycharm
# Gemini Desktop
exec-once = prime-run /usr/bin/gemini-desktop --ozone-platform-hint=auto --disable-gpu --no-sandbox
bindd = $mainMod, G, $d toggle Gemini AI, exec, ~/.local/bin/gemini-toggle.sh
